name: CI

on:
  pull_request:
  push:
    branches: [ main, assignment-dev, assignment-submission ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      # Backend
      DATABASE_URL: "file:./sqlite.db"
      PORT: 4000
      JWT_SECRET: "Something_2123847-super secert-that-cant_breal_2x3"
      SALT_ROUNDS: 10
      NODE_ENV: "development"
      
      # Frontend
      VITE_API_BASE_URL: "http://localhost:4000"

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile=false

      # Setup DB and Run Seed Script
      - name: Setup Database & Seed
        run: |
          cd apps/api
          rm -f sqlite.db  # <--- FORCE DELETE OLD DB
          pnpm db:push
          pnpm seed

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build